//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:12:06 AM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://modernisc.com/api/csd",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ir.itsurena.base.sima.dto.xml.general;
