server:
    port: 8081
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driverClassName: "org.postgresql.Driver"
    username: "hossein"
    password: "123456"
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
#      connectionTimeout: 30000
  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
    hibernate:
      ddl-auto: update
#  autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    template:
      default-receive-queue: tue.sender
      exchange: tue.direct
      routing-key: st.pdeng
    listener:
      simple:
        auto-startup: false
  main:
    allow-bean-definition-overriding: true

hibernate:
  hikari:
   minimumIdle: 5
   maximumPoolSize: 10
   idleTimeout: 30000
