
/*
 This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
 See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 Any modifications to this file will be lost upon recompilation of the source schema.
 Generated on: 2019.02.04 at 11:12:06 AM IRST
*/



package ir.itsurena.base.dto.response;

import ir.itsurena.base.dto.library.SecuritiesType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for GetSecuritiesForSaleResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetSecuritiesForSaleResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modernisc.com/api/csd}AbstractResponseType">
 *       &lt;sequence>
 *         &lt;element name="Securities" type="{http://modernisc.com/api/csd}SecuritiesType"/>
 *         &lt;element name="AvailableBalance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetSecuritiesForSaleResponseType", propOrder = {
    "securities",
    "availableBalance"
})
public class GetSecuritiesForSaleResponseType
    extends AbstractResponseType {

    @XmlElement(name = "Securities", required = true)
    protected SecuritiesType securities;
    @XmlElement(name = "AvailableBalance", required = true)
    protected BigDecimal availableBalance;

    /**
     * Gets the value of the securities property.
     * 
     * @return
     *     possible object is
     *     {@link SecuritiesType }
     *     
     */
    public SecuritiesType getSecurities() {
        return securities;
    }

    /**
     * Sets the value of the securities property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecuritiesType }
     *     
     */
    public void setSecurities(SecuritiesType value) {
        this.securities = value;
    }

    /**
     * Gets the value of the availableBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAvailableBalance() {
        return availableBalance;
    }

    /**
     * Sets the value of the availableBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAvailableBalance(BigDecimal value) {
        this.availableBalance = value;
    }

}
