//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:12:06 AM IRST 
//


package nl.tue.base.dto.request;

import nl.tue.base.dto.library.IdentifierType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransferSecuritiesRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransferSecuritiesRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://modernisc.com/api/csd}AbstractRequestType">
 *       &lt;sequence>
 *         &lt;element name="SecuritiesCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="FromIdentifier" type="{http://modernisc.com/api/csd}IdentifierType"/>
 *         &lt;element name="ToIdentifier" type="{http://modernisc.com/api/csd}IdentifierType"/>
 *         &lt;element name="Iban" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransferSecuritiesRequestType", propOrder = {
    "securitiesCode",
    "count",
    "fromIdentifier",
    "toIdentifier",
    "iban",
    "description"
})
public class TransferSecuritiesRequestType
    extends AbstractRequestType
{

    @XmlElement(name = "SecuritiesCode", required = true)
    protected String securitiesCode;
    @XmlElement(name = "Count")
    protected long count;
    @XmlElement(name = "FromIdentifier", required = true)
    protected IdentifierType fromIdentifier;
    @XmlElement(name = "ToIdentifier", required = true)
    protected IdentifierType toIdentifier;
    @XmlElement(name = "Iban", required = true)
    protected String iban;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the securitiesCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuritiesCode() {
        return securitiesCode;
    }

    /**
     * Sets the value of the securitiesCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuritiesCode(String value) {
        this.securitiesCode = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public long getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(long value) {
        this.count = value;
    }

    /**
     * Gets the value of the fromIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getFromIdentifier() {
        return fromIdentifier;
    }

    /**
     * Sets the value of the fromIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setFromIdentifier(IdentifierType value) {
        this.fromIdentifier = value;
    }

    /**
     * Gets the value of the toIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getToIdentifier() {
        return toIdentifier;
    }

    /**
     * Sets the value of the toIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setToIdentifier(IdentifierType value) {
        this.toIdentifier = value;
    }

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIban() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIban(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
