/*
package rules;
//import nl.tue.base.secondlibraryservicedto.dto.AccountDto
import nl.tue.base.ruleengineservicedto.util.RuleErrorCode;
dialect  "mvel"

rule "1"
    salience 2
    agenda-group "FIRST_LIBRARY"

   when
        $account : AccountDto( balance < 100 )
   then

end


rule "2"
   salience 1
   agenda-group "FIRST_LIBRARY"

   when
        $account : AccountDto( balance > 100 )
   then
        $account.setMessage(RuleErrorCode.ACCOUNT_HIGH_BALANCE.toString());
end*/
