package rules;
import nl.tue.base.ruleengineservicedto.dto.AccountDto
import nl.tue.base.ruleengineservicedto.util.RuleErrorCode;

dialect  "mvel"

rule "3"
    agenda-group "THIRD_LIBRARY"

   when
        $models : AccountDto(balance < 100)
   then
        $models.setMessage(RuleErrorCode.ACCOUNT_LOW_BALANCE.toString());

end



rule "44"
    agenda-group "FOURTH_LIBRARY"

   when
        $models : AccountDto(balance > 10000)
   then
        $models.setMessage(RuleErrorCode.ACCOUNT_HIGH_BALANCE.toString());

end



