
/*
 This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
 See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 Any modifications to this file will be lost upon recompilation of the source schema.
 Generated on: 2019.02.04 at 11:12:06 AM IRST
*/

package nl.tue.base.mq.dto.xml.general;

import nl.tue.base.dto.library.*;
import nl.tue.base.dto.request.*;
import nl.tue.base.dto.response.*;
import org.springframework.stereotype.Component;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@Component
@XmlRegistry
public class MqObjectFactory {

    private static final String NAME_SPACE_URI = "http://modernisc.com/api/csd";

    private static final QName _UpdatePersonResponse_QNAME = new QName(NAME_SPACE_URI, "UpdatePersonResponse");
    private static final QName _CreatePersonResponse_QNAME = new QName(NAME_SPACE_URI, "CreatePersonResponse");
    private static final QName _PingResponse_QNAME = new QName(NAME_SPACE_URI, "PingResponse");
    private static final QName _UnblockAccountRequest_QNAME = new QName(NAME_SPACE_URI, "UnblockAccountRequest");
    private static final QName _PingRequest_QNAME = new QName(NAME_SPACE_URI, "PingRequest");
    private static final QName _UpdateOrganizationResponse_QNAME = new QName(NAME_SPACE_URI, "UpdateOrganizationResponse");
    private static final QName _CreateOrganizationRequest_QNAME = new QName(NAME_SPACE_URI, "CreateOrganizationRequest");
    private static final QName _BlockAccountResponse_QNAME = new QName(NAME_SPACE_URI, "BlockAccountResponse");
    private static final QName _GetOrganizationByIdentifierResponse_QNAME = new QName(NAME_SPACE_URI, "GetOrganizationByIdentifierResponse");
    private static final QName _GetOrganizationsByNameRequest_QNAME = new QName(NAME_SPACE_URI, "GetOrganizationsByNameRequest");
    private static final QName _GetPersonsByNameRequest_QNAME = new QName(NAME_SPACE_URI, "GetPersonsByNameRequest");
    private static final QName _CreatePersonRequest_QNAME = new QName(NAME_SPACE_URI, "CreatePersonRequest");
    private static final QName _GetOrganizationByIdentifierRequest_QNAME = new QName(NAME_SPACE_URI, "GetOrganizationByIdentifierRequest");
    private static final QName _UpdatePersonRequest_QNAME = new QName(NAME_SPACE_URI, "UpdatePersonRequest");
    private static final QName _UnblockAccountResponse_QNAME = new QName(NAME_SPACE_URI, "UnblockAccountResponse");
    private static final QName _GetPersonByIdentifierRequest_QNAME = new QName(NAME_SPACE_URI, "GetPersonByIdentifierRequest");
    private static final QName _UpdateOrganizationRequest_QNAME = new QName(NAME_SPACE_URI, "UpdateOrganizationRequest");
    private static final QName _GetOrganizationsByNameResponse_QNAME = new QName(NAME_SPACE_URI, "GetOrganizationsByNameResponse");
    private static final QName _BlockAccountRequest_QNAME = new QName(NAME_SPACE_URI, "BlockAccountRequest");
    private static final QName _GetPersonByIdentifierResponse_QNAME = new QName(NAME_SPACE_URI, "GetPersonByIdentifierResponse");
    private static final QName _CreateOrganizationResponse_QNAME = new QName(NAME_SPACE_URI, "CreateOrganizationResponse");
    private static final QName _GetPersonsByNameResponse_QNAME = new QName(NAME_SPACE_URI, "GetPersonsByNameResponse");


    public PingRequestType createPingRequestType() {
        return new PingRequestType();
    }

    public UnblockAccountRequestType createUnblockAccountRequestType() {
        return new UnblockAccountRequestType();
    }

    public PingResponseType createPingResponseType() {
        return new PingResponseType();
    }

    public CreatePersonResponseType createCreatePersonResponseType() {
        return new CreatePersonResponseType();
    }

    public UpdatePersonResponseType createUpdatePersonResponseType() {
        return new UpdatePersonResponseType();
    }

    public CreatePersonRequestType createCreatePersonRequestType() {
        return new CreatePersonRequestType();
    }

    public GetPersonsByNameRequestType createGetPersonsByNameRequestType() {
        return new GetPersonsByNameRequestType();
    }

    public GetOrganizationsByNameRequestType createGetOrganizationsByNameRequestType() {
        return new GetOrganizationsByNameRequestType();
    }

    public GetOrganizationByIdentifierResponseType createGetOrganizationByIdentifierResponseType() {
        return new GetOrganizationByIdentifierResponseType();
    }

    public BlockAccountResponseType createBlockAccountResponseType() {
        return new BlockAccountResponseType();
    }

    public CreateOrganizationRequestType createCreateOrganizationRequestType() {
        return new CreateOrganizationRequestType();
    }

    /**
     * Create an instance of {@link UpdateOrganizationResponseType }
     */
    public UpdateOrganizationResponseType createUpdateOrganizationResponseType() {
        return new UpdateOrganizationResponseType();
    }

    /**
     * Create an instance of {@link UnblockAccountResponseType }
     */
    public UnblockAccountResponseType createUnblockAccountResponseType() {
        return new UnblockAccountResponseType();
    }

    /**
     * Create an instance of {@link UpdatePersonRequestType }
     */
    public UpdatePersonRequestType createUpdatePersonRequestType() {
        return new UpdatePersonRequestType();
    }

    /**
     * Create an instance of {@link GetOrganizationByIdentifierRequestType }
     */
    public GetOrganizationByIdentifierRequestType createGetOrganizationByIdentifierRequestType() {
        return new GetOrganizationByIdentifierRequestType();
    }

    /**
     * Create an instance of {@link CreateOrganizationResponseType }
     */
    public CreateOrganizationResponseType createCreateOrganizationResponseType() {
        return new CreateOrganizationResponseType();
    }

    /**
     * Create an instance of {@link GetPersonsByNameResponseType }
     */
    public GetPersonsByNameResponseType createGetPersonsByNameResponseType() {
        return new GetPersonsByNameResponseType();
    }

    /**
     * Create an instance of {@link GetPersonByIdentifierResponseType }
     */
    public GetPersonByIdentifierResponseType createGetPersonByIdentifierResponseType() {
        return new GetPersonByIdentifierResponseType();
    }

    /**
     * Create an instance of {@link BlockAccountRequestType }
     */
    public BlockAccountRequestType createBlockAccountRequestType() {
        return new BlockAccountRequestType();
    }

    /**
     * Create an instance of {@link GetOrganizationsByNameResponseType }
     */
    public GetOrganizationsByNameResponseType createGetOrganizationsByNameResponseType() {
        return new GetOrganizationsByNameResponseType();
    }

    /**
     * Create an instance of {@link UpdateOrganizationRequestType }
     */
    public UpdateOrganizationRequestType createUpdateOrganizationRequestType() {
        return new UpdateOrganizationRequestType();
    }

    /**
     * Create an instance of {@link GetPersonByIdentifierRequestType }
     */
    public GetPersonByIdentifierRequestType createGetPersonByIdentifierRequestType() {
        return new GetPersonByIdentifierRequestType();
    }

    /**
     * Create an instance of {@link PersonType }
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link SecuritiesFeatureType }
     */
    public SecuritiesFeatureType createSecuritiesFeatureType() {
        return new SecuritiesFeatureType();
    }

    /**
     * Create an instance of {@link ErrorType }
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link AccountsType }
     */
    public AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link PartyStatusType }
     */
    public PartyStatusType createPartyStatusType() {
        return new PartyStatusType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link QuantityType }
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link SecuritiesType }
     */
    public SecuritiesType createSecuritiesType() {
        return new SecuritiesType();
    }

    /**
     * Create an instance of {@link PaginationResultType }
     */
    public PaginationResultType createPaginationResultType() {
        return new PaginationResultType();
    }

    /**
     * Create an instance of {@link PaginationType }
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link PrincipalType }
     */
    public PrincipalType createPrincipalType() {
        return new PrincipalType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePersonResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UpdatePersonResponse")
    public JAXBElement<UpdatePersonResponseType> createUpdatePersonResponse(UpdatePersonResponseType value) {
        return new JAXBElement<>(_UpdatePersonResponse_QNAME, UpdatePersonResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePersonResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "CreatePersonResponse")
    public JAXBElement<CreatePersonResponseType> createCreatePersonResponse(CreatePersonResponseType value) {
        return new JAXBElement<>(_CreatePersonResponse_QNAME, CreatePersonResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PingResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "PingResponse")
    public JAXBElement<PingResponseType> createPingResponse(PingResponseType value) {
        return new JAXBElement<>(_PingResponse_QNAME, PingResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnblockAccountRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UnblockAccountRequest")
    public JAXBElement<UnblockAccountRequestType> createUnblockAccountRequest(UnblockAccountRequestType value) {
        return new JAXBElement<>(_UnblockAccountRequest_QNAME, UnblockAccountRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PingRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "PingRequest")
    public JAXBElement<PingRequestType> createPingRequest(PingRequestType value) {
        return new JAXBElement<>(_PingRequest_QNAME, PingRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrganizationResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UpdateOrganizationResponse")
    public JAXBElement<UpdateOrganizationResponseType> createUpdateOrganizationResponse(UpdateOrganizationResponseType value) {
        return new JAXBElement<>(_UpdateOrganizationResponse_QNAME, UpdateOrganizationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrganizationRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "CreateOrganizationRequest")
    public JAXBElement<CreateOrganizationRequestType> createCreateOrganizationRequest(CreateOrganizationRequestType value) {
        return new JAXBElement<>(_CreateOrganizationRequest_QNAME, CreateOrganizationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockAccountResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "BlockAccountResponse")
    public JAXBElement<BlockAccountResponseType> createBlockAccountResponse(BlockAccountResponseType value) {
        return new JAXBElement<>(_BlockAccountResponse_QNAME, BlockAccountResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrganizationByIdentifierResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetOrganizationByIdentifierResponse")
    public JAXBElement<GetOrganizationByIdentifierResponseType> createGetOrganizationByIdentifierResponse(GetOrganizationByIdentifierResponseType value) {
        return new JAXBElement<>(_GetOrganizationByIdentifierResponse_QNAME, GetOrganizationByIdentifierResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrganizationsByNameRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetOrganizationsByNameRequest")
    public JAXBElement<GetOrganizationsByNameRequestType> createGetOrganizationsByNameRequest(GetOrganizationsByNameRequestType value) {
        return new JAXBElement<>(_GetOrganizationsByNameRequest_QNAME, GetOrganizationsByNameRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPersonsByNameRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetPersonsByNameRequest")
    public JAXBElement<GetPersonsByNameRequestType> createGetPersonsByNameRequest(GetPersonsByNameRequestType value) {
        return new JAXBElement<>(_GetPersonsByNameRequest_QNAME, GetPersonsByNameRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePersonRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "CreatePersonRequest")
    public JAXBElement<CreatePersonRequestType> createCreatePersonRequest(CreatePersonRequestType value) {
        return new JAXBElement<>(_CreatePersonRequest_QNAME, CreatePersonRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrganizationByIdentifierRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetOrganizationByIdentifierRequest")
    public JAXBElement<GetOrganizationByIdentifierRequestType> createGetOrganizationByIdentifierRequest(GetOrganizationByIdentifierRequestType value) {
        return new JAXBElement<>(_GetOrganizationByIdentifierRequest_QNAME, GetOrganizationByIdentifierRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePersonRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UpdatePersonRequest")
    public JAXBElement<UpdatePersonRequestType> createUpdatePersonRequest(UpdatePersonRequestType value) {
        return new JAXBElement<>(_UpdatePersonRequest_QNAME, UpdatePersonRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnblockAccountResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UnblockAccountResponse")
    public JAXBElement<UnblockAccountResponseType> createUnblockAccountResponse(UnblockAccountResponseType value) {
        return new JAXBElement<>(_UnblockAccountResponse_QNAME, UnblockAccountResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPersonByIdentifierRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetPersonByIdentifierRequest")
    public JAXBElement<GetPersonByIdentifierRequestType> createGetPersonByIdentifierRequest(GetPersonByIdentifierRequestType value) {
        return new JAXBElement<>(_GetPersonByIdentifierRequest_QNAME, GetPersonByIdentifierRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrganizationRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "UpdateOrganizationRequest")
    public JAXBElement<UpdateOrganizationRequestType> createUpdateOrganizationRequest(UpdateOrganizationRequestType value) {
        return new JAXBElement<>(_UpdateOrganizationRequest_QNAME, UpdateOrganizationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrganizationsByNameResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetOrganizationsByNameResponse")
    public JAXBElement<GetOrganizationsByNameResponseType> createGetOrganizationsByNameResponse(GetOrganizationsByNameResponseType value) {
        return new JAXBElement<>(_GetOrganizationsByNameResponse_QNAME, GetOrganizationsByNameResponseType.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockAccountRequestType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "BlockAccountRequest")
    public JAXBElement<BlockAccountRequestType> createBlockAccountRequest(BlockAccountRequestType value) {
        return new JAXBElement<>(_BlockAccountRequest_QNAME, BlockAccountRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPersonByIdentifierResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetPersonByIdentifierResponse")
    public JAXBElement<GetPersonByIdentifierResponseType> createGetPersonByIdentifierResponse(GetPersonByIdentifierResponseType value) {
        return new JAXBElement<>(_GetPersonByIdentifierResponse_QNAME, GetPersonByIdentifierResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrganizationResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "CreateOrganizationResponse")
    public JAXBElement<CreateOrganizationResponseType> createCreateOrganizationResponse(CreateOrganizationResponseType value) {
        return new JAXBElement<>(_CreateOrganizationResponse_QNAME, CreateOrganizationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPersonsByNameResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = NAME_SPACE_URI, name = "GetPersonsByNameResponse")
    public JAXBElement<GetPersonsByNameResponseType> createGetPersonsByNameResponse(GetPersonsByNameResponseType value) {
        return new JAXBElement<>(_GetPersonsByNameResponse_QNAME, GetPersonsByNameResponseType.class, null, value);
    }

}
