//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 11:12:06 AM IRST 
//


package ir.itsurena.base.dto.request;

import ir.itsurena.base.dto.library.AccountsType;
import ir.itsurena.base.dto.library.IdentifierType;
import ir.itsurena.base.dto.library.PaginationType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAccountsRequestType", propOrder = {
        "accountNumber",
        "securitiesCode",
        "identifier",
        "status",
        "pagination"
})
public class GetAccountsRequestType extends AbstractRequestType {

    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "SecuritiesCode")
    protected String securitiesCode;
    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    @XmlElement(name = "Status")
    protected AccountsType.AccountStatusType status;
    @XmlElement(name = "Pagination", required = true)
    protected PaginationType pagination;


    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    public String getSecuritiesCode() {
        return securitiesCode;
    }

    public void setSecuritiesCode(String value) {
        this.securitiesCode = value;
    }

    public IdentifierType getIdentifier() {
        return identifier;
    }

    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    public AccountsType.AccountStatusType getStatus() {
        return status;
    }

    public void setStatus(AccountsType.AccountStatusType value) {
        this.status = value;
    }

    public PaginationType getPagination() {
        return pagination;
    }

    public void setPagination(PaginationType value) {
        this.pagination = value;
    }

}
